# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tugas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 160, 321, 174))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.hargaLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hargaLineEdit.setObjectName("hargaLineEdit")
        self.gridLayout.addWidget(self.hargaLineEdit, 2, 0, 1, 1)
        self.totalLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.totalLineEdit.setObjectName("totalLineEdit")
        self.gridLayout.addWidget(self.totalLineEdit, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect button click event to the calculation function
        self.pushButton.clicked.connect(self.calculate_total)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Harga Total"))
        self.label_3.setText(_translate("MainWindow", "Masukan Total Jumlah Barang"))
        self.label_2.setText(_translate("MainWindow", "Masukan Harga Barang"))
        self.label.setText(_translate("MainWindow", "Aplikasi Perhitungan Harga Barang"))
        self.label_4.setText(_translate("MainWindow", "Total:"))

    def calculate_total(self):
        try:
            harga = float(self.hargaLineEdit.text())
            jumlah = int(self.totalLineEdit.text())
            total = harga * jumlah
            self.label_4.setText(f"Total: {total}")
        except ValueError:
            self.label_4.setText("Input tidak valid! Pastikan harga dan jumlah barang benar.")
